// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=false, version=6.3.2

//# unitInfo: Provides: Ppx_sexp_conv_lib
//# unitInfo: Requires: Sexplib0__Sexp, Sexplib0__Sexp_conv
//# shape: Ppx_sexp_conv_lib:[[F(1)*,F(1)*,F(1)*,F(2),F(2),F(1),N,N,F(2),N,F(1)*,F(2),F(3),F(2),F(2),N,F(1),F(1),N,N,N,N,N,F(3),F(1),F(1),N,N,N,N]]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Sexplib0_Sexp = global_data.Sexplib0__Sexp,
    Sexplib0_Sexp_conv = global_data.Sexplib0__Sexp_conv,
    t_of_sexp = Sexplib0_Sexp[1],
    sexp_of_t = Sexplib0_Sexp[2],
    sexp_of_t_stack = Sexplib0_Sexp[3],
    equal = Sexplib0_Sexp[4],
    compare = Sexplib0_Sexp[5],
    globalize = Sexplib0_Sexp[6],
    Not_found_s = Sexplib0_Sexp[7],
    Of_sexp_error = Sexplib0_Sexp[8],
    message = Sexplib0_Sexp[9],
    default_indent = Sexplib0_Sexp[10],
    Make_pretty_printing = Sexplib0_Sexp[11],
    pp_hum = Sexplib0_Sexp[12],
    pp_hum_indent = Sexplib0_Sexp[13],
    pp_mach = Sexplib0_Sexp[14],
    pp = Sexplib0_Sexp[15],
    to_string_hum = Sexplib0_Sexp[16],
    to_string_mach = Sexplib0_Sexp[17],
    to_string = Sexplib0_Sexp[18],
    to_buffer_hum = Sexplib0_Sexp[19],
    to_buffer_mach = Sexplib0_Sexp[20],
    to_buffer = Sexplib0_Sexp[21],
    to_buffer_gen = Sexplib0_Sexp[22],
    Pretty_printing_helpers_privat = Sexplib0_Sexp[23],
    to_string_hum_stack = Sexplib0_Sexp[24],
    to_string_mach_stack = Sexplib0_Sexp[25],
    to_string_stack = Sexplib0_Sexp[26],
    of_float_style = Sexplib0_Sexp[27],
    of_int_style = Sexplib0_Sexp[28],
    Private = Sexplib0_Sexp[29],
    t_sexp_grammar = Sexplib0_Sexp_conv[80];
   runtime.caml_register_global
    (2,
     [0,
      [0,
       t_of_sexp,
       sexp_of_t,
       sexp_of_t_stack,
       equal,
       compare,
       globalize,
       Not_found_s,
       Of_sexp_error,
       message,
       default_indent,
       Make_pretty_printing,
       pp_hum,
       pp_hum_indent,
       pp_mach,
       pp,
       to_string_hum,
       to_string_mach,
       to_string,
       to_buffer_hum,
       to_buffer_mach,
       to_buffer,
       to_buffer_gen,
       Pretty_printing_helpers_privat,
       to_string_hum_stack,
       to_string_mach_stack,
       to_string_stack,
       of_float_style,
       of_int_style,
       Private,
       t_sexp_grammar]],
     "Ppx_sexp_conv_lib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3NleHBfY29udl9saWIuY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjoxMCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJwcHhfc2V4cF9jb252X2xpYi5jbWEuanMiLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIl0sInNvdXJjZXNDb250ZW50IjpbIigqIGdlbmVyYXRlZCBjb2RlICopIl0sIm5hbWVzIjpbInJ1bnRpbWUiLCJnbG9iYWxfZGF0YSIsIlNleHBsaWIwX1NleHAiLCJTZXhwbGliMF9TZXhwX2NvbnYiLCJ0X29mX3NleHAiLCJzZXhwX29mX3QiLCJzZXhwX29mX3Rfc3RhY2siLCJlcXVhbCIsImNvbXBhcmUiLCJnbG9iYWxpemUiLCJOb3RfZm91bmRfcyIsIk9mX3NleHBfZXJyb3IiLCJtZXNzYWdlIiwiZGVmYXVsdF9pbmRlbnQiLCJNYWtlX3ByZXR0eV9wcmludGluZyIsInBwX2h1bSIsInBwX2h1bV9pbmRlbnQiLCJwcF9tYWNoIiwicHAiLCJ0b19zdHJpbmdfaHVtIiwidG9fc3RyaW5nX21hY2giLCJ0b19zdHJpbmciLCJ0b19idWZmZXJfaHVtIiwidG9fYnVmZmVyX21hY2giLCJ0b19idWZmZXIiLCJ0b19idWZmZXJfZ2VuIiwiUHJldHR5X3ByaW50aW5nX2hlbHBlcnNfcHJpdmF0IiwidG9fc3RyaW5nX2h1bV9zdGFjayIsInRvX3N0cmluZ19tYWNoX3N0YWNrIiwidG9fc3RyaW5nX3N0YWNrIiwib2ZfZmxvYXRfc3R5bGUiLCJvZl9pbnRfc3R5bGUiLCJQcml2YXRlIiwidF9zZXhwX2dyYW1tYXIiXSwibWFwcGluZ3MiOiJJQUFBQSxVQUFBO0FBQUEsSUFBQUMsY0FBQTtBQUFBLElBQUFDLGdCQUFBO0FBQUEsSUFBQUMscUJBQUE7QUFBQSxJQUFBQyxZQUFBO0FBQUEsSUFBQUMsWUFBQTtBQUFBLElBQUFDLGtCQUFBO0FBQUEsSUFBQUMsUUFBQTtBQUFBLElBQUFDLFVBQUE7QUFBQSxJQUFBQyxZQUFBO0FBQUEsSUFBQUMsY0FBQTtBQUFBLElBQUFDLGdCQUFBO0FBQUEsSUFBQUMsVUFBQTtBQUFBLElBQUFDLGlCQUFBO0FBQUEsSUFBQUMsdUJBQUE7QUFBQSxJQUFBQyxTQUFBO0FBQUEsSUFBQUMsZ0JBQUE7QUFBQSxJQUFBQyxVQUFBO0FBQUEsSUFBQUMsS0FBQTtBQUFBLElBQUFDLGdCQUFBO0FBQUEsSUFBQUMsaUJBQUE7QUFBQSxJQUFBQyxZQUFBO0FBQUEsSUFBQUMsZ0JBQUE7QUFBQSxJQUFBQyxpQkFBQTtBQUFBLElBQUFDLFlBQUE7QUFBQSxJQUFBQyxnQkFBQTtBQUFBLElBQUFDLGlDQUFBO0FBQUEsSUFBQUMsc0JBQUE7QUFBQSxJQUFBQyx1QkFBQTtBQUFBLElBQUFDLGtCQUFBO0FBQUEsSUFBQUMsaUJBQUE7QUFBQSxJQUFBQyxlQUFBO0FBQUEsSUFBQUMsVUFBQTtBQUFBLElBQUFDLGlCQUFBIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
