// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=false, version=6.3.2

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3RkcHB4X3NoaW0uY21hLmpzIiwic2VjdGlvbnMiOltdfQ==
