// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=cma, use-js-string=false, version=6.3.2

//# unitInfo: Provides: Sexp_type
//# shape: Sexp_type:[[]]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.caml_register_global(0, [0, [0]], "Sexp_type");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2V4cF90eXBlLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6OCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJzZXhwX3R5cGUuY21hLmpzIiwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSJdLCJuYW1lcyI6WyJydW50aW1lIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQSIsImlnbm9yZUxpc3QiOlswXX19XX0=
