// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=false, version=6.3.2

//# unitInfo: Provides: Ppx_portable_runtime
//# shape: Ppx_portable_runtime:[F(1)*]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function ignore(a){return 0;}
   runtime.caml_register_global(0, [0, ignore], "Ppx_portable_runtime");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3BvcnRhYmxlX3J1bnRpbWUuY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjo4LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6InBweF9wb3J0YWJsZV9ydW50aW1lLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsImlnbm9yZSJdLCJtYXBwaW5ncyI6Ik9BQUFBLFVBQUE7QUFBQSxZQUFBQyxPQUFBIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
