// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=cma, use-js-string=false, version=6.3.2

//# unitInfo: Provides: Jane_street_headers
//# shape: Jane_street_headers:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.caml_register_global(0, [0], "Jane_street_headers");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiamFuZV9zdHJlZXRfaGVhZGVycy5jbWEuanMiLCJzZWN0aW9ucyI6W3sib2Zmc2V0Ijp7ImxpbmUiOjgsImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoiamFuZV9zdHJlZXRfaGVhZGVycy5jbWEuanMiLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIl0sInNvdXJjZXNDb250ZW50IjpbIigqIGdlbmVyYXRlZCBjb2RlICopIl0sIm5hbWVzIjpbInJ1bnRpbWUiXSwibWFwcGluZ3MiOiJPQUFBQSxVQUFBIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
