// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=cma, use-js-string=false, version=6.3.2

//# unitInfo: Provides: Ppx_enumerate_lib
//# shape: Ppx_enumerate_lib:[[]]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.caml_register_global(0, [0, [0]], "Ppx_enumerate_lib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2VudW1lcmF0ZV9saWIuY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjo4LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6InBweF9lbnVtZXJhdGVfbGliLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSJdLCJtYXBwaW5ncyI6Ik9BQUFBLFVBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
